# Generated by Django 5.0.1 on 2024-03-08 22:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('strozone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='injured_list_table',
            fields=[
                ('injured_list_id', models.AutoField(primary_key=True, serialize=False)),
                ('player_name', models.CharField(max_length=500)),
                ('position', models.CharField(max_length=50)),
                ('updated', models.DateTimeField()),
                ('injury_body_part', models.CharField(max_length=100)),
                ('injury_description', models.CharField(max_length=1000)),
                ('crc_id', models.CharField(max_length=1000)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='strozone.team_table')),
            ],
        ),
    ]
