# Generated by Django 5.0.1 on 2024-02-29 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('strozone', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='league_t22e',
        ),
    ]
